# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Velvet v3"
product_name = "Velvet v3"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "ergohaven"
chip = "nrf52840"
# usb_enable = true

[layout]
rows = 4
cols = 12
layers = 2
keymap = [
    [
        ["Q", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "P",],
        ["Q", "MT(A, LShift)", "LT(5, S)", "LT(1, D)", "LT(3, F)", "G", "H", "LT(4, J)", "LT(2, K)", "LT(6, L)", "MT(Semicolon, LShift)", "Q",],
        ["Q", "MT(Z, LGui)", "MT(X, LCtrl)", "MT(C, LAlt)", "V", "B", "N", "M", "MT(Comma, LAlt)", "MT(Dot, LCtrl)", "MT(Slash, LGui)", "Q",],
        ["Q", "_", "_", "_", "Enter", "Space", "Backspace", "Tab", "_", "_", "_", "Q",],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_",],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_",],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_",],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_",],
    ],
]
[storage]

[ble]
enabled = true

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
matrix_type = "normal"
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation
# row2col = true
input_pins = ["P0_30", "P0_10", "P0_9", "P0_24"]
output_pins = ["P0_2", "P1_13", "P0_28", "P0_3", "P1_10", "P1_11"]

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 2
col_offset = 2
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["P0_30", "P0_10", "P0_9", "P0_24"]
output_pins = ["P0_2", "P1_13", "P0_28", "P0_3", "P1_10", "P1_11"]

